SUPABASE_URL = "https://iojddemcsygazpraaafa.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvamRkZWNtc3lnYXpwcmFhYWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjMyODMsImV4cCI6MjA2NDc5OTI4M30.fZf9hdlM7WvJwnowWXp_1iUyiF-9NRlmXGKRPUo4aes"
